volumes:
  pg_data_kittygram:
  static_kittygram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: ilyak475/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
  frontend:
    image: ilyak475/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: ilyak475/kittygram_gateway
    env_file: .env
    ports:
      - '${EXTERNAL_PORT}:80'
    volumes:
      - static_kittygram:/staticfiles/
    environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT}
