volumes:
  pg_data_kittygram:
  static_kittygram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_kittygram:/staticfiles/
    ports:
      - "${EXTERNAL_PORT}:80"
